# Generated by Django 2.2.4 on 2019-10-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discussao',
            fields=[
                ('postagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.Postagem')),
                ('titulo', models.CharField(default='', max_length=100)),
            ],
            bases=('forum.postagem',),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('postagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.Postagem')),
                ('titulo', models.CharField(default='', max_length=50)),
            ],
            bases=('forum.postagem',),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_para_postagem', to='forum.Postagem')),
                ('pergunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta_para_pergunta', to='forum.Pergunta')),
            ],
        ),
    ]
