# Generated by Django 2.2.4 on 2019-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
