# Generated by Django 2.2.4 on 2019-10-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191001_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='resposta',
            name='is_resposta',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
