# Generated by Django 2.2.4 on 2019-11-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20191102_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='forum.Postagem'),
        ),
    ]
