# Generated by Django 2.2.4 on 2019-11-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20191103_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='forum.Postagem'),
        ),
    ]
