# Generated by Django 2.2.4 on 2019-11-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20191103_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['-data_publicacao']},
        ),
    ]
