# Generated by Django 2.2.4 on 2019-11-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20191126_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['is_resposta', '-data_publicacao']},
        ),
    ]
