# Generated by Django 2.2.4 on 2019-11-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20191126_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['-is_resposta', '-data_publicacao']},
        ),
    ]
